### ISSUE TITLE
[BUG] wrong typecheck in execute method after using zod transform

### ISSUE THREAD

**Issue by QingjiaTsang** [TheEdoRan/next-safe-action#275] opened 2024-09-25 15:39 UTC
### Are you using the latest version of this library?

- [x] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

**actions/property.ts**
```
'use server'
import { Property } from "@prisma/client"
import { addPropertyActionSchema } from "@/schema/property.zod"

import prisma from "@/libs/prisma"
import { flattenValidationErrors } from "next-safe-action"
import { authAction } from "@/libs/actions/safeAction"


export const addProperty = authAction
  .schema(addPropertyActionSchema, {
    handleValidationErrorsShape: (errors) => flattenValidationErrors(errors).fieldErrors
  })
  .action(async ({ ctx, parsedInput }) => {

  })
```

**property.zod.ts**
```
const basicSchema = z.object({
  name: z.string().min(1, { message: "Name is required" }),
  description: z.string().min(1, { message: "Description is required" }),
  typeId: z.string().min(1, { message: "Type is required" }),
  statusId: z.string().min(1, { message: "Status is required" }),
  // I transform the price field from string to number here
  price: z.string()
    .refine((val) =>
      validator.isCurrency(val, {
        allow_decimal: true,
        digits_after_decimal: [1, 2],
        allow_negatives: false,
      }), { message: "Invalid price format" })
    .transform(val => Number(val))
})

// other form schemas...

// here's the schema used for form data validation
export const addPropertyFormSchema = z.object({
  basic: basicSchema,
  // other form schemas...
})

// here's the schema that I put into the schema method of next-safe-action
export const addPropertyActionSchema = addPropertyFormSchema.omit({ pictures: true }).extend({
  pictures: z.array(z.string()).min(1, { message: "At least one picture is required" }),
})
```

<img width="787" alt="image" src="https://github.com/user-attachments/assets/f4dfdb1c-85a4-47bf-941a-462495ea2488">
<img width="922" alt="image" src="https://github.com/user-attachments/assets/6b21eafa-de6a-4171-a8db-2aaae9aaa038">
<img width="749" alt="image" src="https://github.com/user-attachments/assets/f593194e-cd2c-41e1-81c4-e82c3f690c5b">

the thrown error as follow:
Argument of type '{ pictures: string[]; basic: { name: string; description: string; typeId: string; statusId: string; price: number; }; location: { address: string; city: string; state: string; zip: string; landmarks: string; country: string; }; features: { ...; }; contact: { ...; }; }' is not assignable to parameter of type '{ basic: { name: string; description: string; typeId: string; statusId: string; price: string; }; location: { address: string; city: string; state: string; zip: string; landmarks: string; country: string; }; features: { ...; }; pictures: string[]; contact: { ...; }; }'.
  The types of 'basic.price' are incompatible between these types.
    Type 'number' is not assignable to type 'string'.

### Reproduction steps

1. Create a form with something like Price field and transform it from string into number by Zod schema
2. Put the Zod schema to the schema method of next-safe-action
3. When you use the safe action in the client you will see the type error.

### Expected behavior

the type of action param will be consistent with Zod schema even after transforming

### Link to a minimal reproduction of the issue

https://github.com/QingjiaTsang/reproduce-typecheck-bug

### Operating System

macOS Ventura 13.6.9

### Library version

7.9.3

### Next.js version

14.2.13

### Node.js version

20.13.1

**Comment by TheEdoRan** [comment] 2024-09-26 09:35
This is correct. The inferred client input type is the input before transforms, so `z.string()`. Zod performs the transformation after parsing, so you'll get the correct `number` type for `price` on the server, inside `parsedInput`.

**Comment by QingjiaTsang** [comment] 2024-09-26 09:50
So this is a feature instead of a bug? It seems it's not working with intuition.

**Comment by TheEdoRan** [comment] 2024-09-26 09:53
It's not a feature either, it's how Zod works. Since transformations are performed after the input is parsed, it expects the type you defined before `transform`, you can try the same thing without next-safe-action and you'll see the same exact behavior.

**Comment by QingjiaTsang** [comment] 2024-09-26 09:57
If so, then maybe it's not a good practice to transform the form field data, right?

**Comment by TheEdoRan** [comment] 2024-09-26 11:38
I think it makes sense sometimes, it really depends on the context and the scope. By the way, closing this issue since it's not a bug of the library.

**Closed by TheEdoRan** 2024-09-26 11:38 UTC
Labels: bug
