### ISSUE TITLE
[ASK] How do I avoid FetchError: "TypeError: Cannot redefine property: $$id"

### ISSUE THREAD

**Issue by John-Dennehy** [TheEdoRan/next-safe-action#56] opened 2024-01-24 18:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Library version (optional)

6.0.2

### Ask a question

I assume I have made a silly error, but I keep getting a "Fetch Error" when running execute from useAction hook.  

Everything works fine if I run the db query `insertGroup(values)` instead of `execute`, but the minute I try and use useAction I get `"TypeError: Cannot redefine property: $$id"`

I'm following [developedbyed](https://www.youtube.com/@developedbyed) s tutorial, if that helps: https://www.youtube.com/watch?v=UKupfEuUc1M&t=71s 

```ts
// safe-server-actions-client.ts

import { createSafeActionClient } from "next-safe-action"
export const serverActionClient = createSafeActionClient()
export default serverActionClient
```

```ts
/// create-group-action.ts
"use server"

import { insertGroupSchema } from "@/server/data/schema"
import { revalidatePath } from "next/cache"
import { insertGroup } from "../queries/groups"
import { serverActionClient } from "./utils/safe-sever-actions-client"

type ActionSuccess = { success: true; status: "success" }
type ActionError = { success: false; status: "error"; errorMessage: string }
type ActionResponse = ActionSuccess | ActionError

export const createGroupAction = serverActionClient(insertGroupSchema, async (formData): Promise<ActionResponse> => {
  if (!formData) return { success: false, status: "error", errorMessage: "No form data" }

  await insertGroup(formData)
  revalidatePath("/")
  revalidatePath("/groups")
  return { success: true, status: "success" }
})

export default createGroupAction
```

```ts
// 
"use client"

import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form"
import { groupsTable, insertGroupSchema } from "@/server/data/schema"
import { DevTool } from "@hookform/devtools"
import { zodResolver } from "@hookform/resolvers/zod"
import { Table } from "drizzle-orm"
import { ControllerRenderProps, useForm } from "react-hook-form"
import { z } from "zod"
import { Button } from "../ui/button"
import { Checkbox } from "../ui/checkbox"
import { toast } from "sonner"
import createGroupAction from "@/server/actions/create-group-action"
import { useAction } from "next-safe-action/hooks"
import { insertGroup } from "@/server/queries/groups"

import { FormMap } from "@/app/form-hooks"
import { Input } from "../ui/input"
import { Textarea } from "../ui/textarea"

export const newGroupFormMap: FormMap = {
  fields: [
    {
      name: "name",
      label: "Group Name",
      description: "This is the name of the group.",
      Component: Input,
    },
    {
      name: "description",
      label: "Group Description",
      description: "This is the description of the group.",
      Component: Textarea,
      componentProps: { placeholder: "GroupDescription" },
    },
    {
      name: "logoUrl",
      label: "Group Logo URL",
      description: "This is the URL of the group logo, including the prefix (for example https://)",
      Component: Input,
      componentProps: { placeholder: "https://example.com/logo.png" },
    },
    // {
    //   name: "active",
    //   label: "Group Active",
    //   description: "This is whether the group is active.",
    //   Component: Checkbox,
    //   componentProps: {},
    // },
  ],
} as const

const defaultValidationSchema = insertGroupSchema.pick({
  name: true,
  description: true,
  active: true,
})

type NewGroupFormProps = {
  tableSchema?: Table
  validationSchema?: any
  formMap?: typeof newGroupFormMap
}
export default function NewGroupForm({
  tableSchema = groupsTable,
  validationSchema = defaultValidationSchema,
  formMap = newGroupFormMap,
}: NewGroupFormProps) {
  const { execute, result, status } = useAction(createGroupAction, {
    onSuccess: (_data, { name }) => {
      toast.success(`Success: Group ${name} created`)
    },
    onError: (error, input) => {
      if (error.fetchError) toast.error(`Fetch Error: ${error.fetchError}. Failed to create ${input.name}`)
      if (error.serverError) {
        console.error(`${error.serverError}`)
        toast.error(`Server Error: Failed to create ${input.name}`)
      }
      if (error.validationErrors) toast.error(`Validation errors: ${error.validationErrors}`)
    },
  })
  const form = useForm<z.input<typeof validationSchema>>({
    resolver: zodResolver(validationSchema),
  })

  async function handleValid(values: z.output<typeof validationSchema>) {
    execute(values)
  }

  const handleInvalid = () => {
    // TODO: handle form submission error
    toast.error("Group creation failed")
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(handleValid, handleInvalid)} className="flex flex-col gap-4">
        {formMap.fields.map((formField) => {
          const { Component, componentProps, name, label, description } = formField

          const getProps = (field: ControllerRenderProps) => {
            let props = { ...componentProps }

            //	add additional props that require `field` value for Checkbox
            if (Component === Checkbox)
              props = {
                ...componentProps,
                checked: field.value,
                onCheckedChange: field.onChange,
              }

            return { ...field, ...props }
          }

          return (
            <FormField
              key={name}
              control={form.control}
              name={name}
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{label}</FormLabel>
                  <FormControl>
                    <Component {...getProps(field)} />
                  </FormControl>
                  <FormDescription>{description}</FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />
          )
        })}
        <Button aria-disabled={status === "executing"} type="submit">
          Submit
        </Button>
      </form>
      {/* <DevTool control={form.control} /> */}
    </Form>
  )
}
```

**Comment by John-Dennehy** [comment] 2024-01-24 20:37
The more I try and investigate this I think it has something to do with how actions are being compiled. Specifically this  function in my `.next/server/chunks/` folder:
```ts
function createActionProxy(id, action) {
    return (0, _serveredge.registerServerReference)(action, id, null);
} //# sourceMappingURL=action-proxy.js.map
```

**Comment by TheEdoRan** [comment] 2024-01-24 23:21
Well, that's pretty unusual. I don't use Drizzle but it should not happen, never happened to me using Prisma/Kysely. Can you please provide a minimal reproduction example in a repo, so I can investigate this issue? Thank you.

**Comment by John-Dennehy** [comment] 2024-01-25 14:33
Annoyingly, so far I have been unable to recreate the issue in a new repo.  As I add complexity, I'll let you know if it crops up again.

**Comment by John-Dennehy** [comment] 2024-01-26 16:17
I can't believe what seems to have actually caused this issue!!

Works fine
```ts
import GroupList from "@/components/group-list";
import { db } from "@/server/db";
import groupsTable from "@/server/db/schema";

export async function HomePage() {
  const groups = await db.select().from(groupsTable);

  return (
    <main className="container mx-auto">
      <div className="flex flex-col gap-4">
        <h1>Home</h1>
        <GroupList groups={groups} />
      </div>
    </main>
  );
}

export default HomePage;
```

Also works fine
```ts
"use server";

import GroupList from "@/components/group-list";
import { db } from "@/server/db";
import groupsTable from "@/server/db/schema";

export default async function HomePage() {
  const groups = await db.select().from(groupsTable);

  return (
    <main className="container mx-auto">
      <div className="flex flex-col gap-4">
        <h1>Home</h1>
        <GroupList groups={groups} />
      </div>
    </main>
  );
}
```

BUT - using "use server" AND having the default export declared at the end, causes the error. This code causes the error:
```ts
"use server";

import GroupList from "@/components/group-list";
import { db } from "@/server/db";
import groupsTable from "@/server/db/schema";

export async function HomePage() {
  const groups = await db.select().from(groupsTable);

  return (
    <main className="container mx-auto">
      <div className="flex flex-col gap-4">
        <h1>Home</h1>
        <GroupList groups={groups} />
      </div>
    </main>
  );
}

export default HomePage;
```

**Comment by TheEdoRan** [comment] 2024-01-28 11:41
Thank you for your tests! So this is a Next.js issue, right? Can we close this one and track [this PR](https://github.com/vercel/next.js/pull/54654)?

**Comment by John-Dennehy** [comment] 2024-01-28 12:26
Agree this is likely an issue for Next.js to fix.  Useful one to be aware of though!

**Comment by TheEdoRan** [comment] 2024-01-28 13:58
> Whod have thought exporting named and default would cause such issues?

Every day we find something new in this amazing Server Actions world! 😅

Thank you again for your work, I'll close this issue since it's a framework related one, and probably fixed in the next release.

**Closed by TheEdoRan** 2024-01-28 13:58 UTC
Labels: question
