### ISSUE TITLE
[BUG] Schema parsing breaks in edge runtime

### ISSUE THREAD

**Issue by Xexr** [TheEdoRan/next-safe-action#105] opened 2024-04-24 11:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Library version (optional)

7.0.0-next.28

### Ask a question

Hey @TheEdoRan 

I'm back, it's been a while, but fantastic to see how much next-safe-action has come on since the early days.

I'm trying to move to v7 to use the excellent middleware chaining and specifically to setup Sentry.

I'm using the latest next.28 release but keep getting this runtime error:

[TypeError: A dynamic import callback was not specified.] {
  code: 'ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING'
}

As far as I can tell, it happens when I specify a schema and try and access parsedInput.

If I use an action which doesn't provide a schema, I don't get the error.

I'm using the latest node v20 LTS (I was using v18 LTS before, but that led to a segmentation fault error when using next-safe-action).

Other key packages:

"next": "14.2.2",
"@typeschema/zod": "^0.13.3",
"zod": "^3.23.4"
"typescript": "^5.4.5"

Any thoughts? I'm at a loss.

Many thanks

**Comment by TheEdoRan** [comment] 2024-04-24 11:48
Hi @Xexr, nice to see you back, thank you for your kind words. Regarding the issue, can you please provide a link to a minimal reproduction repo/StackBlitz environment so I can investigate on it? Thanks.

**Comment by Xexr** [comment] 2024-04-24 17:58
Sure, here's a minimal reproduction.

The issue is the edge runtime, it doesn't work with edge enabled:

https://github.com/Xexr/next-safe-action-v7

**Comment by TheEdoRan** [comment] 2024-04-25 02:18
I tracked down the issue to TypeSchema `validate` function, which is what parses and validates client input(s), a fundamental part of this library. I'm going to open an issue in the TypeSchema repo, but I don't know if this one is easy fixable. Furthermore, Vercel is apparently [abandoning edge rendering](https://twitter.com/leeerob/status/1780705942734331983).

**Comment by Xexr** [comment] 2024-04-25 06:27
Thanks @TheEdoRan 

I thought it was probably due to typeschema as that seemed liked a significant change. 

Note that Vercel are 'abandoning' edge for their own implementation of next, eg on v0 etc but they haven't stated that they're removing it from next or the vercel platform itself. Lee clarifies further down the thread. 

They state that the v20 node runtime is faster but I don't think that's conclusively proven generically vs just their implementation yet. Indeed it's counter to my own experience. Edge is still far faster and cheaper. I also fence it regionally so don't have the db round trip issue he talks about. 

Theo has a great video on it, worth a watch if you're interested. 

Point being, it's not dead yet.

I'd love to move to v7, it sounds great otherwise. 

Let's see what the typeschema folks come back with.

**Comment by TheEdoRan** [comment] 2024-04-25 12:06
Thanks for the insight. If the issue is not easily fixable on the TypeSchema side, I'll export the same safe action client stuff from the `/compat` path, that will just support Zod as validation library, and actually use its parse function instead of the TypeSchema one.

**Comment by TaylorFacen** [comment] 2024-05-07 03:10
> Thanks for the insight. If the issue is not easily fixable on the TypeSchema side, I'll export the same safe action client stuff from the `/zod` path, that will just support Zod as validation library, and actually use its parse function instead of the TypeSchema one.

Hi, following this issue as I'm seeing it on my end as well. Has this already been implemented?

**Comment by Xexr** [comment] 2024-05-07 23:17
It seems to be working well so far on next.36 with the /zod path export

Thanks very much for this, super helpful @TheEdoRan 🙂

**Comment by TheEdoRan** [comment] 2024-05-07 23:33
@Xexr oh nice! Wanted to test the new version with a proper project to see if everything worked as expected, but it seems you've already done it for me. So you confirm that everything is working with no issues whatsoever? Thanks!

By the way, here's the new [troubleshooting page](https://next.next-safe-action.dev/docs/troubleshooting/errors-with-typeschema) on the website.

**Comment by TaylorFacen** [comment] 2024-05-08 02:45
It's working in my project as well. Thank you so much!

**Comment by TheEdoRan** [comment] 2024-05-08 02:57
> It's working in my project as well. Thank you so much!

Glad to hear that @TaylorFacen! Gonna close this issue since the problem seems to be solved with `/zod` import.

**Closed by TheEdoRan** 2024-05-08 02:57 UTC
Labels: bug

**Comment by Xexr** [comment] 2024-05-08 21:10
It's been working well for me so far - no major issues.

The docs are looking good too, easy to understand.

I love how the middleware chaining enables different clients that progressively add more context where needed.

One thing I've struggled with is getting Sentry to work properly. I've followed the example you gave on another thread.

But no issues were ever logged if I just used Sentry's server action instrumentation as you documented.

I think it might be another edge related issue, see another issue I opened with Sentry should anyone else have the same problem:

https://github.com/getsentry/sentry-javascript/issues/11884

I've got it working by explicitly adding the following to handleServerErrorLog as well as the instrumentation:

```
Sentry.captureException(e);
await Sentry.flush();
```

It works now and issues are captured, but I'm not convinced this is working exactly as they intended - I think withServerActionInstrumentation is supposed to automatically log errors without the need to call captureException seperately.

Anyways, great stuff Edo!

**Comment by TheEdoRan** [comment] 2024-07-20 12:12
A bit late, but this issue has been solved in [v7.2.0](https://github.com/TheEdoRan/next-safe-action/releases/tag/v7.2.0). next-safe-action now ships with built-in support for multiple validation libraries, at the time of this writing Zod (the default one), Valibot and Yup. Now you can use libraries other than Zod with the Edge Runtime. More information about that in [this discussion](https://github.com/TheEdoRan/next-safe-action/discussions/201) and on [this page](https://next-safe-action.dev/docs/recipes/validation-libraries-support) of the website.
